node_modules
**/node_modules
.pnpm-store

dist
**/dist
.turbo
**/.turbo
.cache
**/.cache
.next
**/.next
generated
**/generated

.env
.env.*
!.env.example
.git
.gitignore
*.log

README.md
docs
coverage
**/__tests__
**/*.test.ts
**/*.spec.ts

.vinext
**/.vinext
.wrangler
**/.wrangler
