/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 85f5060d72be211b3e67efe74c043fdc)
interface __BaseEnv_Env {
  CF_VERSION_METADATA: WorkerVersionMetadata;
  ASSETS: Fetcher;
  NODE_ENV: "production";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV">> {}
}
