packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  dotenv-cli: ^11.0.0
  oxlint: 1.76.0
  oxlint-tsgolint: 7.0.2001
  prettier: ^3.8.1
  typescript: ^7.0.2
  "@types/node": ^22.13.11

  # Misc
  zod: ^4
  superjson: ^2.2.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.17.0
  "@trpc/tanstack-react-query": ^11.17.0
  "@trpc/server": ^11.17.0

  # React
  react: 19.2.3
  react-dom: 19.2.3
  "@types/react": ~19.2.2
  "@types/react-dom": ~19.1.7

  # Auth
  better-auth: ^1.6.29
  "@better-auth/expo": ^1.6.29
  "@better-auth/stripe": ^1.6.29

catalogs:
  expo:
    typescript: ~6.0.3
