packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  dotenv-cli: ^11.0.0
  eslint: ^8.57.0
  prettier: ^3.5.3
  typescript: ^5.9.3

  # Misc
  zod: ^4
  superjson: ^2.2.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.8.1
  "@trpc/tanstack-react-query": ^11.8.1
  "@trpc/server": ^11.8.1

  # React
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": 19.1.10
  "@types/react-dom": 19.1.6

  # Auth
  better-auth: ^1.4.8
  "@better-auth/expo": ^1.4.8
  "@better-auth/stripe": ^1.4.8
