/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2a94c0cfab5203a169120f4ac2a0c5bd)
interface __BaseEnv_Env {
  ENVIRONMENT: "production";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server.workerd");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
